# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdfundingpostproposal',
            name='end_datetime',
        ),
        migrations.AddField(
            model_name='crowdfundingpostproposal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
