# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0002_auto_20161226_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfundingpostproposal',
            name='num_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
