# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0004_auto_20161229_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfundingpostproposal',
            name='voting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.CrowdFundingProposalVoting'),
        ),
    ]
