# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0006_auto_20161229_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdfundingproposalvoting',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='crowdfundingproposalvoting',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='crowdfundingproposalvoting',
            name='vote_type',
            field=models.CharField(blank=True, choices=[(b'UP', b'Upvote'), (b'DN', b'DownVote')], max_length=2),
        ),
    ]
