# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0007_auto_20161229_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crowdfundingproposalvoting',
            old_name='propoasl_id',
            new_name='proposal_id',
        ),
    ]
