# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0010_auto_20161230_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextendedforfunding',
            name='user_type',
            field=models.CharField(blank=True, choices=[(b'FR', b'Facilitator'), (b'MR', b'Member')], max_length=7),
        ),
    ]
