# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0012_auto_20161230_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdFundingMemberGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='userextendedforfunding',
            name='group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.CrowdFundingMemberGroup'),
        ),
    ]
