# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0013_auto_20161230_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdFundingProposalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_success_perc', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='crowdfundingpostproposal',
            name='state',
            field=models.CharField(choices=[(b'DT', b'Draft'), (b'CD', b'Closed')], default=b'DT', max_length=2),
        ),
    ]
