# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0017_auto_20170103_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextendedforfunding',
            name='user_image',
            field=models.ImageField(blank=True, upload_to=b'media/'),
        ),
    ]
