# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0019_auto_20170109_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdfundingproposalvoting',
            name='author',
        ),
        migrations.RemoveField(
            model_name='crowdfundingproposalvoting',
            name='proposal_id',
        ),
        migrations.RemoveField(
            model_name='crowdfundingpostproposal',
            name='group_type',
        ),
        migrations.DeleteModel(
            name='CrowdFundingProposalVoting',
        ),
    ]
